package com.fid.job.util;

import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;

public class GenerateAllPasswordHashes {
    public static void main(String[] args) {
        BCryptPasswordEncoder encoder = new BCryptPasswordEncoder();
        
        System.out.println("-- ====================================================================");
        System.out.println("-- VERIFIED BCRYPT HASHES GENERATED BY JAVA");
        System.out.println("-- ====================================================================");
        System.out.println();
        
        // 각 사용자별 비밀번호와 해시 생성
        String[][] users = {
            {"admin", "admin"},
            {"user01", "test123"},
            {"freelancer01", "free123"},
            {"pm_leader", "pm123"},
            {"testuser", "1234"}
        };
        
        for (String[] user : users) {
            String username = user[0];
            String password = user[1];
            String hash = encoder.encode(password);
            
            System.out.println("-- Username: " + username + " / Password: " + password);
            System.out.println("UPDATE users SET password_hash = '" + hash + "' WHERE username = '" + username + "';");
            System.out.println();
        }
        
        System.out.println("-- 확인 쿼리");
        System.out.println("SELECT username, LEFT(password_hash, 30) as hash_preview FROM users WHERE username IN ('admin', 'user01', 'freelancer01', 'pm_leader', 'testuser');");
    }
}