spring:
  application:
    name: jobkorea-billboard-backend
  
  # Database Configuration
  datasource:
    url: jdbc:mariadb://192.168.0.109:3306/jobtracker
    username: root
    password: 
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
  
  # Redis Configuration (Optional - for session management)
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  
  # JPA/Hibernate (disabled since we're using MyBatis)
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  
  # Jackson Configuration
  jackson:
    default-property-inclusion: non-null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

# MyBatis Configuration - PM7 프로젝트용
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fid.job.model
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    whitelabel:
      enabled: false

# JWT Configuration - PM7 프로젝트용
jwt:
  secret: am9ia29yZWEtYmlsbGJvYXJkLXNlY3JldC1rZXktMjAyNC12ZXJ5LWxvbmctc2VjcmV0LWZvci1qd3Qtc2lnbmluZw==  # Base64 encoded secret
  expiration: 86400000  # 24 hours in milliseconds
  refresh-expiration: 604800000  # 7 days in milliseconds

# Security Configuration
security:
  jwt:
    secret: jobkorea-billboard-secret-key-2024-very-long-secret-for-jwt-signing
    expiration: 2592000000  # 30 days in milliseconds
    refresh-expiration: 7776000000  # 90 days in milliseconds

# CORS Configuration
cors:
  allowed-origins:
    - http://localhost:3000
    - http://127.0.0.1:3000
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers:
    - "*"
  allow-credentials: true
  max-age: 3600

# Logging Configuration - PM7 프로젝트용
logging:
  level:
    com.fid.job: DEBUG
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.mybatis: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/pm7-application.log

# Management/Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

# SpringDoc OpenAPI 설정
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

# Custom Application Properties
app:
  name: JobKorea Billboard Backend
  version: 1.0.0
  description: JobKorea Billboard 백엔드 API 서버
  upload:
    path: uploads/
    max-file-size: 10MB
    max-request-size: 50MB