spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.0.109:3306/jobtracker?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: ~Asy10131227
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 300000
      connection-timeout: 20000
      validation-timeout: 5000
      max-lifetime: 1200000
      connection-test-query: SELECT 1
      connection-init-sql: SET NAMES utf8mb4
      data-source-properties:
        useUnicode: true
        characterEncoding: UTF-8
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  security:
    user:
      name: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD:admin}

  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: false

server:
  port: 8080
  tomcat:
    max-threads: 200
    min-spare-threads: 20
    max-connections: 10000
    accept-count: 100
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/plain
    min-response-size: 2048

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # SQL 로그 출력
  type-aliases-package: com.example.pm7.model  # 모델 클래스 패키지 추가

jwt:
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  expiration: 86400000  # 24시간
  refresh-token-expiration: 604800000

logging:
  level:
    root: INFO
    com.zaxxer.hikari: WARN
    com.example.pm7: DEBUG
    org.springframework.web: WARN
    org.springframework.jdbc: TRACE
    org.mybatis: TRACE
    com.example.pm7.mapper: TRACE
    org.springframework.jdbc.core: TRACE
    org.springframework.transaction: DEBUG
    org.springframework.security: WARN
    org.apache.ibatis: TRACE
    org.apache.ibatis.executor: TRACE
    org.apache.ibatis.executor.statement: TRACE
    org.apache.ibatis.executor.parameter: TRACE
    org.apache.ibatis.executor.resultset: TRACE
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}" 
  file:
    name: logs/application.log
    max-size: 10MB
    max-history: 30

file:
  upload:
    path: /uploads/notice 

# SpringDoc 설정 추가
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  show-actuator: true 